### ISSUE TITLE
Generates 0 valid structures with pre-trained checkpoints

### ISSUE THREAD

**Issue by AdeeshKolluru** [lantunes/CrystaLLM#2]
I tried to generate cifs from both small and large models and get 0 valid structures on evaluation. 

I followed the process of downloading all necessary files as mentioned in README and then ran - 
`python bin/generate_cifs.py --model crystallm_v1_large --prompts prompts_v1_test.tar.gz --out gen_v1_large_raw.tar.gz --device cuda --num-gens 1 `
`python bin/evaluate_cifs.py gen_v1_large_raw.tar.gz -o gen_v1_large_eval.csv`
Output - 
![image](https://github.com/lantunes/CrystaLLM/assets/43401571/0826ebbf-14de-40ee-acb3-88a643599d52)

Here's the generated file - 
[gen_v1_large_raw.tar.gz](https://github.com/lantunes/CrystaLLM/files/14358344/gen_v1_large_raw.tar.gz)

Please let me know if I'm missing anything or if I should do anything differently, thanks!

**Comment by lantunes** [comment]
Hi, thanks for reporting this. I downloaded the attached file, and ran the same `python bin/evaluate_cifs.py gen_v1_large_raw.tar.gz -o gen_v1_large_eval.csv` command, and this is the output I got:
```
space group consistent: 10176/10286 (0.989)
atom site multiplicity consistent: 10275/10286 (0.999)
avg. bond length reasonableness score: 0.9918 ± 0.0570
bond lengths reasonable: 9901/10286 (0.963)
num valid: 9820/10286 (0.95)
longest valid generated length: 2,023
avg. valid generated length: 340.343 ± 88.637
```
I've recently updated the `bin/evaluate_cifs.py` script so that it can print more information during processing. Can you update your local copy of the code, and try running:
```
python bin/evaluate_cifs.py gen_v1_large_raw.tar.gz -o gen_v1_large_eval.csv --debug
```
(Note the `--debug` flag.) Please post here the error messages you see (if any) while this command is running. 

Also, please run `pip freeze > environment.txt` in your Python environment and attach the resulting `environment.txt` file here.

**Comment by AdeeshKolluru** [comment]
Thanks for your quick response! I am able to reproduce your results now after pulling the latest version and re-creating the env.
![image](https://github.com/lantunes/CrystaLLM/assets/43401571/40a3ac48-89cc-454e-a0d0-fe42e97135df)

**Comment by yanliang3612** [comment]
hi, @AdeeshKolluru, @lantunes  , do you know where i can find `prompts_v1_test.tar.gz` file

**Comment by lantunes** [comment]
Hi,

The `prompts_v1_test.tar.gz` file was not part of the file upload to Zenodo, however, the file can be generated using this command:
```
python bin/make_prompts.py cifs_v1_test.pkl.gz -o prompts_v1_test.tar.gz
```
